<a href="https://colab.research.google.com/github/goulartdea/dio_aulas/blob/main/ouvidoria.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Prefeitura de POA - Dados Abertos - Ouvidoria

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
ouvidoria = pd.read_csv('/content/ouvidoria.csv', sep=';')

In [ ]:
ouvidoria

,data_extracao,protocolo,descricao,sigla,statussolicitacao,dataregistro,datafinalprevista,dataenvioresposta,tipofim
0,2023-10-01 00:00:00.000,000039-19-66,FINANÇAS,SMF,RESPONDIDO,2019-09-03 17:23:22.830,2019-10-03 23:59:59.999,2019-09-24 15:35:10.293,RESPOSTA_CONCLUSIVA
1,2023-10-01 00:00:00.000,000040-19-15,FINANÇAS,SMF,RESPONDIDO,2019-09-03 17:40:17.733,2019-10-03 23:59:59.999,2019-09-24 16:04:35.887,RESPOSTA_CONCLUSIVA
2,2023-10-01 00:00:00.000,000049-19-06,INFRAESTRUTURA URBANISMO,SMSURB,RESPONDIDO,2019-09-04 10:27:04.595,2019-10-04 23:59:59.999,2019-09-11 16:59:26.681,RESPOSTA_CONCLUSIVA
3,2023-10-01 00:00:00.000,000069-19-06,INFRAESTRUTURA URBANISMO,NaN,RESPONDIDO,2019-09-06 11:30:34.711,2019-10-08 23:59:59.999,2019-10-08 11:10:31.986,RESPOSTA_CONCLUSIVA
4,2023-10-01 00:00:00.000,000076-19-82,OUTRO TEMA,NaN,RESPONDIDO,2019-09-06 20:05:58.939,2019-10-08 23:59:59.999,2019-09-11 17:17:07.397,RESPOSTA_CONCLUSIVA
...,...,...,...,...,...,...,...,...,...
28780,2023-10-01 00:00:00.000,063601-23-35,NaN,NaN,EM_AVALIACAO,2023-09-29 15:46:56.961,2023-10-31 23:59:59.999,NaN,NaN
28781,2023-10-01 00:00:00.000,063605-23-56,NaN,NaN,EM_AVALIACAO,2023-09-29 16:20:54.825,2023-10-31 23:59:59.999,NaN,NaN
28782,2023-10-01 00:00:00.000,063608-23-10,NaN,NaN,EM_AVALIACAO,2023-09-29 17:52:04.122,2023-10-31 23:59:59.999,NaN,NaN
28783,2023-10-01 00:00:00.000,063623-23-31,NaN,NaN,EM_AVALIACAO,2023-09-29 21:49:09.217,2023-10-31 23:59:59.999,NaN,NaN
28784,2023-10-01 00:00:00.000,063632-23-23,NaN,NaN,CANCELADO,2023-09-30 13:11:30.865,2023-10-31 23:59:59.999,NaN,CANCELADO

In [ ]:
ouvidoria.isnull().sum()

In [ ]:
ouvidoria.info()

In [ ]:
ouvidoria.columns.values

Filtragem de dados

In [ ]:
ouvidoria.describe()

Verificação de quantas denuncias estão pendentes no canal da ouvidoria da cidade de Porto Alegre, RS

In [ ]:
#Seleção na coluna "status" somente as denuncias que estão como "em avaliação", que considerei como pendentes
selecao_ouvidoria = ouvidoria[ouvidoria['statussolicitacao'].str.contains('EM_AVALIACAO', case=False)]

In [ ]:
selecao_ouvidoria

,data_extracao,protocolo,descricao,sigla,statussolicitacao,dataregistro,datafinalprevista,dataenvioresposta,tipofim
27274,2023-10-01 00:00:00.000,059564-23-82,SANEAMENTO,NaN,EM_AVALIACAO,2023-07-13 10:26:38.367,2023-10-30 23:59:59.999,NaN,NaN
28217,2023-10-01 00:00:00.000,063472-23-35,AUXÍLIO AO SERVIDOR,NaN,EM_AVALIACAO,2023-09-27 09:01:49.799,2023-10-27 23:59:59.999,NaN,NaN
28223,2023-10-01 00:00:00.000,063549-23-19,NaN,NaN,EM_AVALIACAO,2023-09-28 14:00:38.550,2023-10-30 23:59:59.999,NaN,NaN
28225,2023-10-01 00:00:00.000,063571-23-16,NaN,NaN,EM_AVALIACAO,2023-09-29 08:15:00.249,2023-10-31 23:59:59.999,NaN,NaN
28226,2023-10-01 00:00:00.000,063578-23-01,NaN,NaN,EM_AVALIACAO,2023-09-29 09:35:09.277,2023-10-31 23:59:59.999,NaN,NaN
28227,2023-10-01 00:00:00.000,063581-23-66,NaN,NaN,EM_AVALIACAO,2023-09-29 09:49:14.503,2023-10-31 23:59:59.999,NaN,NaN
28228,2023-10-01 00:00:00.000,063615-23-06,NaN,NaN,EM_AVALIACAO,2023-09-29 20:14:33.522,2023-10-31 23:59:59.999,NaN,NaN
28229,2023-10-01 00:00:00.000,063624-23-99,NaN,NaN,EM_AVALIACAO,2023-09-29 22:02:29.559,2023-10-31 23:59:59.999,NaN,NaN
28230,2023-10-01 00:00:00.000,063635-23-96,NaN,NaN,EM_AVALIACAO,2023-09-30 18:07:25.536,2023-10-31 23:59:59.999,NaN,NaN
28401,2023-10-01 00:00:00.000,063506-23-75,SANEAMENTO,NaN,EM_AVALIACAO,2023-09-27 17:44:24.735,2023-10-30 23:59:59.999,NaN,NaN
28405,2023-10-01 00:00:00.000,063541-23-86,NaN,NaN,EM_AVALIACAO,2023-09-28 13:26:52.651,2023-10-30 23:59:59.999,NaN,NaN
28407,2023-10-01 00:00:00.000,063550-23-78,NaN,NaN,EM_AVALIACAO,2023-09-28 14:15:59.765,2023-10-30 23:59:59.999,NaN,NaN
28408,2023-10-01 00:00:00.000,063553-23-32,NaN,NaN,EM_AVALIACAO,2023-09-28 14:30:22.043,2023-10-30 23:59:59.999,NaN,NaN
28409,2023-10-01 00:00:00.000,063558-23-01,NaN,NaN,EM_AVALIACAO,2023-09-28 15:40:26.892,2023-10-30 23:59:59.999,NaN,NaN
28410,2023-10-01 00:00:00.000,063560-23-18,NaN,NaN,EM_AVALIACAO,2023-09-28 16:02:42.573,2023-10-30 23:59:59.999,NaN,NaN
28411,2023-10-01 00:00:00.000,063574-23-80,NaN,NaN,EM_AVALIACAO,2023-09-29 09:02:22.534,2023-10-31 23:59:59.999,NaN,NaN
28412,2023-10-01 00:00:00.000,063576-23-95,NaN,NaN,EM_AVALIACAO,2023-09-29 09:23:47.250,2023-10-31 23:59:59.999,NaN,NaN
28413,2023-10-01 00:00:00.000,063579-23-59,NaN,NaN,EM_AVALIACAO,2023-09-29 09:43:57.157,2023-10-31 23:59:59.999,NaN,NaN
28414,2023-10-01 00:00:00.000,063585-23-87,NaN,NaN,EM_AVALIACAO,2023-09-29 12:37:05.022,2023-10-31 23:59:59.999,NaN,NaN
28415,2023-10-01 00:00:00.000,063621-23-25,NaN,NaN,EM_AVALIACAO,2023-09-29 21:05:51.484,2023-10-31 23:59:59.999,NaN,NaN
28416,2023-10-01 00:00:00.000,063628-23-00,NaN,NaN,EM_AVALIACAO,2023-09-30 10:18:47.190,2023-10-31 23:59:59.999,NaN,NaN
28417,2023-10-01 00:00:00.000,063629-23-68,NaN,NaN,EM_AVALIACAO,2023-09-30 10:22:04.251,2023-10-31 23:59:59.999,NaN,NaN
28418,2023-10-01 00:00:00.000,063633-23-81,NaN,NaN,EM_AVALIACAO,2023-09-30 14:17:31.467,2023-10-31 23:59:59.999,NaN,NaN
28504,2023-10-01 00:00:00.000,062313-23-54,FINANÇAS,NaN,EM_AVALIACAO,2023-09-05 13:55:14.878,2023-10-05 23:59:59.999,NaN,NaN
28638,2023-10-01 00:00:00.000,063476-23-56,AUXÍLIO AO SERVIDOR,NaN,EM_AVALIACAO,2023-09-27 09:59:12.885,2023-10-27 23:59:59.999,NaN,NaN
28689,2023-10-01 00:00:00.000,063503-23-02,ANIMAIS,NaN,EM_AVALIACAO,2023-09-27 15:57:43.201,2023-10-31 23:59:59.999,NaN,NaN
28692,2023-10-01 00:00:00.000,063556-23-05,NaN,NaN,EM_AVALIACAO,2023-09-28 15:31:01.241,2023-10-30 23:59:59.999,NaN,NaN
28693,2023-10-01 00:00:00.000,063557-23-53,NaN,NaN,EM_AVALIACAO,2023-09-28 15:39:22.650,2023-10-30 23:59:59.999,NaN,NaN
28694,2023-10-01 00:00:00.000,063561-23-76,NaN,NaN,EM_AVALIACAO,2023-09-28 16:21:44.113,2023-10-30 23:59:59.999,NaN,NaN
28695,2023-10-01 00:00:00.000,063582-23-14,NaN,NaN,EM_AVALIACAO,2023-09-29 09:56:19.460,2023-10-31 23:59:59.999,NaN,NaN
28696,2023-10-01 00:00:00.000,063590-23-58,NaN,NaN,EM_AVALIACAO,2023-09-29 12:59:58.420,2023-10-31 23:59:59.999,NaN,NaN
28697,2023-10-01 00:00:00.000,063591-23-06,NaN,NaN,EM_AVALIACAO,2023-09-29 13:04:48.284,2023-10-31 23:59:59.999,NaN,NaN
28698,2023-10-01 00:00:00.000,063592-23-64,NaN,NaN,EM_AVALIACAO,2023-09-29 13:20:35.177,2023-10-31 23:59:59.999,NaN,NaN
28699,2023-10-01 00:00:00.000,063634-23-39,NaN,NaN,EM_AVALIACAO,2023-09-30 15:02:56.449,2023-10-31 23:59:59.999,NaN,NaN
28761,2023-10-01 00:00:00.000,063513-23-52,NaN,NaN,EM_AVALIACAO,2023-09-27 19:21:28.228,2023-10-27 23:59:59.999,NaN,NaN
28766,2023-10-01 00:00:00.000,063548-23-61,NaN,NaN,EM_AVALIACAO,2023-09-28 13:57:03.681,2023-10-30 23:59:59.999,NaN,NaN
28767,2023-10-01 00:00:00.000,063551-23-26,NaN,NaN,EM_AVALIACAO,2023-09-28 14:20:36.922,2023-10-30 23:59:59.999,NaN,NaN
28768,2023-10-01 00:00:00.000,063562-23-24,NaN,NaN,EM_AVALIACAO,2023-09-28 16:23:49.155,2023-10-30 23:59:59.999,NaN,NaN
28769,2023-10-01 00:00:00.000,063563-23-82,NaN,NaN,EM_AVALIACAO,2023-09-28 18:32:57.877,2023-10-30 23:59:59.999,NaN,NaN
28770,2023-10-01 00:00:00.000,063565-23-97,NaN,NaN,EM_AVALIACAO,2023-09-28 19:09:58.100,2023-10-30 23:59:59.999,NaN,NaN
28771,2023-10-01 00:00:00.000,063575-23-37,NaN,NaN,EM_AVALIACAO,2023-09-29 09:12:52.301,2023-10-31 23:59:59.999,NaN,NaN
28772,2023-10-01 00:00:00.000,063587-23-93,NaN,NaN,EM_AVALIACAO,2023-09-29 12:40:22.555,2023-10-31 23:59:59.999,NaN,NaN
28773,2023-10-01 00:00:00.000,063604-23-09,NaN,NaN,EM_AVALIACAO,2023-09-29 15:54:56.163,2023-10-31 23:59:59.999,NaN,NaN
28774,2023-10-01 00:00:00.000,063611-23-85,NaN,NaN,EM_AVALIACAO,2023-09-29 18:31:01.758,2023-10-31 23:59:59.999,NaN,NaN
28775,2023-10-01 00:00:00.000,063625-23-46,NaN,NaN,EM_AVALIACAO,2023-09-30 06:02:06.131,2023-10-31 23:59:59.999,NaN,NaN
28776,2023-10-01 00:00:00.000,063626-23-04,NaN,NaN,EM_AVALIACAO,2023-09-30 06:49:40.625,2023-10-31 23:59:59.999,NaN,NaN
28778,2023-10-01 00:00:00.000,063564-23-30,NaN,NaN,EM_AVALIACAO,2023-09-28 19:07:14.378,2023-10-30 23:59:59.999,NaN,NaN
28779,2023-10-01 00:00:00.000,063583-23-72,NaN,NaN,EM_AVALIACAO,2023-09-29 11:20:36.090,2023-10-31 23:59:59.999,NaN,NaN
28780,2023-10-01 00:00:00.000,063601-23-35,NaN,NaN,EM_AVALIACAO,2023-09-29 15:46:56.961,2023-10-31 23:59:59.999,NaN,NaN
28781,2023-10-01 00:00:00.000,063605-23-56,NaN,NaN,EM_AVALIACAO,2023-09-29 16:20:54.825,2023-10-31 23:59:59.999,NaN,NaN
28782,2023-10-01 00:00:00.000,063608-23-10,NaN,NaN,EM_AVALIACAO,2023-09-29 17:52:04.122,2023-10-31 23:59:59.999,NaN,NaN
28783,2023-10-01 00:00:00.000,063623-23-31,NaN,NaN,EM_AVALIACAO,2023-09-29 21:49:09.217,2023-10-31 23:59:59.999,NaN,NaN

In [ ]:
# Quantidade de denúncias pendentes no momento da extração dos dados: 52 aguardando resposta
selecao_ouvidoria.shape

(52, 9)

Transformando um dataframe em arquivo csv

In [ ]:
selecao_ouvidoria.to_csv('pendencias_ouvidoria', index=False)